version: '3.7'

services:
  minio:
    container_name: minio
    image: minio/minio
    volumes:
    - ./storage/minio:/data
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    ports:
    - "9000:9000"
    - "9001:9001"
    command: server /data --console-address ":9001"
  mongo:
    image: mongo
  back:
    container_name: back
    build:
      context: back
      dockerfile: Dockerfile
    volumes: 
      - './back:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - S3_KEY=minio_access_key
      - S3_SECRET=minio_secret_key
      - S3_HOST=http://minio:9000
      - S3_BUCKET=tts-data
      - MONGO_URL=mongodb://mongo:27017/dataset
      - NODE_PORT=3000
    depends_on: 
      - mongo
    links: 
      - mongo
  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './front:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_HOST=http://localhost:3002/
    depends_on: 
      - back
    links: 
      - back
